service: lysenko-syrupmg-ru

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-client-s3

custom:
  client:
    bucketName: lysenko.syrupmg.ru
